import type { Metadata } from "next";
import localFont from "next/font/local";
import "./css/globals.css";
import "./css/common.scss";
import "./css/layout.scss";
import "./css/banner.scss";
import "./css/form.scss";
import "./css/recommend-page.scss";
import "./css/detail-page.scss";
import "./css/cocktail-detail.css";
import "./css/login.css";
import "./css/ingredient-detail.css";
import "./css/upload.css";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 930",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${pretendard.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
